-------------------------------------------------
----------- CRIANDO BANCO E TABELAS -------------
-------------------------------------------------

CREATE DATABASE DOGSANDPEOPLE;
USE DOGSANDPEOPLE;

DROP TABLE IF EXISTS DONOS;

CREATE TABLE DONOS(
	ID_DONO INT NOT NULL IDENTITY(1, 1),
	NOME_DONO VARCHAR(255) NOT NULL,

	CONSTRAINT PK_ID_DONOS PRIMARY KEY (ID_DONO),
	CONSTRAINT IDX_ID_DONOS UNIQUE (ID_DONO)
);

DROP TABLE IF EXISTS CAES;

CREATE TABLE CAES(
	ID_CAO INT NOT NULL IDENTITY(1, 1),
	NOME_CAO VARCHAR(255) NOT NULL,
	RACA_CAO VARCHAR(255) NOT NULL,

	CONSTRAINT PK_ID_CAES PRIMARY KEY (ID_CAO),
	CONSTRAINT IDX_ID_CAES UNIQUE (ID_CAO)
)

DROP TABLE IF EXISTS CAES_DONOS;

CREATE TABLE CAES_DONOS(
	ID_DONO INT,
	ID_CAO INT
);
